language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
  provider: pages
  local-dir: output
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  on:
    branch: master
